name: Deploy
on:
  push:
    branches:
      - 'develop'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: 'true'
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install
        run: yarn install
      - name: Test
        run: npm run test:ci
      - name: Build
        run: |
          npm run build
      - uses: jeffreytse/jekyll-deploy-action@v0.5.1
        with:
          provider: 'github'
          token: ${{ secrets.SHARED_BOT_GITHUB_TOKEN }} # rss-to-twitter require PAT for page_build event
          branch: 'master'          # Default is gh-pages for github provider
          jekyll_src: './'           # Default is root directory
          jekyll_cfg: '_config.yml'  # Default is _config.yml
          jekyll_baseurl: ''         # Default is according to _config.yml
          cname: 'jser.info'         # Default is to not use a cname
