name: Deploy
on:
  push:
    branches:
      - 'develop'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: 'true'
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install
        run: yarn install
      - name: Test
        run: npm run test:ci
      - name: Build
        run: |
          npm run build
      - name: Git Identify
        run: |
          git config --global user.email "azuciao@gmail.com"
          git config --global user.name "azu"
      - uses: jeffreytse/jekyll-deploy-action@d90a835c3b0d80402bd8f7a8c7cf694bb75c05dd # https://github.com/jeffreytse/jekyll-deploy-action/issues/64
        with:
          provider: 'github'
          token: ${{ secrets.GITHUB_TOKEN }} # It's your Personal Access Token(PAT)
          branch: 'master'          # Default is gh-pages for github provider
          jekyll_src: './'           # Default is root directory
          jekyll_cfg: '_config.yml'  # Default is _config.yml
          jekyll_baseurl: ''         # Default is according to _config.yml
          bundler_ver: '2.1.4'         # Default is latest bundler version
          cname: 'jser.info'         # Default is to not use a cname
