name: rss-to-twitter
on:
  page_build
jobs:
  twitter:
    runs-on: ubuntu-latest
    # if github.event.build.error.message is not null, it means that the build failed. Skip it
    if: ${{ github.event.build.error.message == null }}
    steps:
      # https://github.com/azu/rss-to-twitter
      - uses: azu/rss-to-twitter@v1
        with:
          RSS_URL: "https://jser.info/rss/"
          TWEET_TEMPLATE: '更新しました！ "%title%" %url%'
          UPDATE_WITHIN_MINUTES: 1440 # post items that are published within 1day
          TWITTER_APIKEY: ${{ secrets.TWITTER_APIKEY }}
          TWITTER_APIKEY_SECRET: ${{ secrets.TWITTER_APIKEY_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
