name: rss-to-twitter
on:
  page_build
jobs:
  twitter:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/azu/rss-to-twitter
      - uses: azu/rss-to-twitter@v1
        with:
          RSS_URL: "https://jser.info/rss/"
          TWEET_TEMPLATE: '更新しました！ "%title%" %url%'
          UPDATE_WITHIN_MINUTES: 15 # post items that are published within 15 minutes
          TWITTER_APIKEY: ${{ secrets.TWITTER_APIKEY }}
          TWITTER_APIKEY_SECRET: ${{ secrets.TWITTER_APIKEY_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
